POST http://localhost:3001/sign-up HTTP/1.1
content-type: application/json

{
  "fname": "bb",
  "lname": "bbbb",
  "email": "aa@aa.a",
  "password": "pas"
}

###

POST http://localhost:3001/sign-in HTTP/1.1
content-type: application/json

{
  "email": "aa@aa.a",
  "password": "aaO"
}

###
POST  http://localhost:3001/createProducts
content-type: application/json

{
  "productName": "sample",
  "price": 12,
  "userId": 1,
  "category": "H",
  "content": "Boulalalalala",
  "picture": "okay.png"
}

###
GET http://localhost:3001/products
content-type: application/json

###

GET http://localhost:3001/createProducts/1
content-type: application/json

###
GET http://localhost:3001/users
content-type: application/json

###
GET http://localhost:3001/users/2
content-type: application/json