POST http://localhost:3001/sign-up HTTP/1.1
content-type: application/json

{
  "fname": "bb",
  "lname": "bbbb",
  "email": "aa@aa.a",
  "password": "pas"
}

###

POST http://localhost:3001/sign-in HTTP/1.1
content-type: application/json

{
  "email": "aa@aa.a",
  "password": "aaO"
}

###
POST  http://localhost:3001/products
content-type: application/json

{
    "userId": 3,
    "productName": "Jean Noir",
    "content": "Jean Slime noir",
    "price": "12.00",
    "category": "f",
    "picture": "https://media.cyrillus.fr/Pictures/cyrillus/55422/jean-slim-enduit-femme.jpg?width=542",
    "active": 1,
}

###
GET http://localhost:3001/products
content-type: application/json

###

GET http://localhost:3001/products/3
content-type: application/json

###
GET http://localhost:3001/users
content-type: application/json

###
PUT http://localhost:3001/products/1
content-type: application/json

###
DELETE http://localhost:3001/products/1
content-type: application/json
