POST http://localhost:3001/sign-up HTTP/1.1
content-type: application/json

{
  "fname": "aa",
  "lname": "Wed",
  "email": "aa@aa.a",
  "password": "pass"
}

###

POST http://localhost:3001/sign-in HTTP/1.1
content-type: application/json

{
  "email": "aa@aa.a",
  "password": "aaO"
}

###
POST  http://localhost:3001/createProducts
content-type: application/json

{
  "productName": "sample",
  "price": 12,
  "userId": 1,
  "category": "H",
  "content": "Boulalalalala",
  "picture": "okay.png"
}
